#!/usr/bin/python3

from pathlib import Path

# DATABASE ATTRIBUTES
DBNAME = "Grocery.db"
DBPATH = Path( DBNAME )

# WINDOW ATTRIBUTES
INITIALHEIGHT = 300
INITIALWIDTH = 500
INITIALX = 500
INITIALY = 500
